development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://bnyrnehvabphoj:UmmS7OXpox3VVjOyGxW8tNf-XL@ec2-54-235-179-112.compute-1.amazonaws.com:5432/d7444auf5ojuq9
